### ISSUE TITLE
Unable start production server in Windows

### ISSUE THREAD

**Issue by krissh-codes** [KrishnaMoorthy12/babel-express-template#3]
> set NODE_ENV=production && export NODE_ENV=production && node build/server.js

```
'export' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app-backend@0.0.1 start: `set NODE_ENV=production && export NODE_ENV=production && node build/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app-backend@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
Log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle my-app-backend@0.0.1~prestart: my-app-backend@0.0.1
6 info lifecycle my-app-backend@0.0.1~start: my-app-backend@0.0.1
7 verbose lifecycle my-app-backend@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle my-app-backend@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Krish\github\babel-express-template\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\TDM-GCC-64\bin;C:\Users\Krish\AppData\Local\Microsoft\WindowsApps;C:\Users\Krish\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\GitHub CLI\;C:\Users\Krish\AppData\Roaming\npm;C:\Program Files\adb;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\MongoDB\Server\4.4\bin
9 verbose lifecycle my-app-backend@0.0.1~start: CWD: C:\Users\Krish\github\babel-express-template
10 silly lifecycle my-app-backend@0.0.1~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'set NODE_ENV=production && export NODE_ENV=production && node build/server.js'
10 silly lifecycle ]
11 silly lifecycle my-app-backend@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle my-app-backend@0.0.1~start: Failed to exec start script
13 verbose stack Error: my-app-backend@0.0.1 start: `set NODE_ENV=production && export NODE_ENV=production && node build/server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid my-app-backend@0.0.1
15 verbose cwd C:\Users\Krish\github\babel-express-template
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error my-app-backend@0.0.1 start: `set NODE_ENV=production && export NODE_ENV=production && node build/server.js`
22 error Exit status 1
23 error Failed at the my-app-backend@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by krissh-codes** [comment]
addressed https://github.com/KrishnaMoorthy12/babel-express-template/commit/e113c03c96cc5b27b168cb987b8ebb6df5b6b1c4

For production environments, manually set up system-wide NODE_ENV
